-- Role
CREATE TABLE IF NOT EXISTS role (
    id INT PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Modul C (Fathur, Ruben)
-- Jabatan
CREATE TABLE IF NOT EXISTS jabatan (
    id INT PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Departemen
CREATE TABLE IF NOT EXISTS departemen (
    id INT PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Status Aktif Pegawai
CREATE TABLE IF NOT EXISTS status_aktif_pegawai (
    id VARCHAR(2) PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Shift
CREATE TABLE IF NOT EXISTS shift (
    id VARCHAR(2) PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    jam_masuk TIME WITH TIME ZONE NOT NULL,
    jam_pulang TIME WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Hari
CREATE TABLE IF NOT EXISTS hari (
    id INT PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Alasan Cuti
CREATE TABLE IF NOT EXISTS alasan_cuti (
    id VARCHAR(2) PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Modul D (Leon)
